### ISSUE TITLE
怎么用GPU调用这些代码哈？

### ISSUE THREAD

**Issue by IamTonyMa** [WHUH-ML/Chondrosarcoma#2]
您好，我觉得您写的这些代码非常有用，我用一个大数据集，所以想可不可以在GPU上运行，看您写的随机那部里用到了cuda，不知道您是用GPU训练的吗？

**Comment by WHUH-ML** [comment]
我是用cpu训练的。如果你要想用里面的deepsurv、nmtlr等方法，可以使用pytorch框架的[pycox](https://github.com/havakv/pycox)包，它支持cuda
